language: node_js
node_js:
  - node # uses most recent stable node version
services:
  - postgresql # starts up postgres
addons:
  postgresql: "9.6" # highest available postgres version on Travis
dist: trusty # uses trusty environment
sudo: false # when on trusty, uses Docker containers for speed
notifications:
  email:
    on_success: change # default: change (only when going from broken to fixed)
    on_failure: always # default: always (which is annoying, as it should be)
install:
  - npm ci # faster, goes only from package-lock
before_script:
  - psql -c 'create database "deployment-exercise-test";' -U postgres # remember to change this name if you change it elsewhere (e.g. package.json)
before_deploy: # omit node_modules, since we set skip_cleanup below
  - rm -rf node_modules
deploy: # see README for details on these keys
  # prevents travis from deleting the build
  skip_cleanup: true
  provider: heroku
  # app should be your heroku app name; see README
  app: fsa-deployment
  # the secure key indicates an encrypted value; see README
  api_key:
    secure: covNwCgfCLrZQULzuNruJQHZrpAYv3QITu9YVX5x6b6XjrJvjLVNHArzH6CzSOnkkX7zINOllHSd7A/lnjckcn1a+pyR+u8YycnAtafSX32TSS4d0fWxk23U5dsm5Jj83m9JOpc+36gmXquP81x2+5S1XRwCkQWkW47qw/Qa2RS2jl1rJ9KyKZDgySe0tjCuAno7cx073e+sNN0R3wc6MJ6XVasIgtnyrZLlrtIYXxaOSM4EEZBKPFfnQUDo9ELM2+LvnI8zJNEHMn/VeSdVbYn3UFNOtbALF8IgEoOyIIz14/nswzaAVgOV5fYlHy19ciqqJdglVCFFcp7CtK2esgILq2ytbUKmTPNrAW5BcHzgb2dYsXGlkAWozFi0IWkUKBG3ubmJdhEN0roIPErZhC6pvb6DIRkaSbTDSaz4zJfyBNPIgAyzxhfKY6k8odUJTOBotHUFqapsSIj2iTS3jv0e/TLOFzk6lD514+BRrFMVyhwnHAyoW7Dx7Zb2wwsSkvq8jOeh/GzlNcm3mqvyy/ft84AziqO2zkpYWTtDaSOBPYt1e1OnNIk/kDZe/6HgDTrcghW/7Wr0Fa2ZkRLJ0mxfSxAkgTB2KrYCt97SURjFs/lbN7qdgDTvGzmNgIJvBSO4DrgVOt2DwtHphrrQQMCF/myURAC99ARQS99NUcg=
